[package]
name = "payroll"
version = "1.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
poseidon2-ligero = { version = "1.0.0", path = "../poseidon2-ligero" }
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
ed25519-dalek = "2"
sha2 = "0.10"
