// Generator: emits Montgomery-form BN254-Fr constants for the Soroban poseidon1 crate,
// and a set of test vectors — both derived from the authoritative reference poseidon1.js.
const fs = require('fs');
const path = require('path');

// Source of truth: the vendored poseidon-lite reference. Resolved relative to this script
// (…/privacypool-contracts/soroban/contracts/poseidon1/scripts → repo root is 5 up).
const REPO_ROOT = path.resolve(__dirname, '../../../../..');
const REF = path.join(REPO_ROOT, 'ligeroclear/public/assets/poseidon1.js');
const src = fs.readFileSync(REF, 'utf8');

// Pull the RAW2 literal ({"C":[...],"M":[...]}) straight out of the reference file.
const m = src.match(/const RAW2 = (\{.*?\});/s);
if (!m) throw new Error('could not find RAW2 in reference');
const RAW2 = JSON.parse(m[1]);

const F = 21888242871839275222246405745257275088548364400416034343698204186575808495617n;
const R = 1n << 256n;

function b64ToBig(b64) {
  const buf = Buffer.from(b64, 'base64'); // 32 bytes, big-endian
  let v = 0n;
  for (const byte of buf) v = (v << 8n) | BigInt(byte);
  return v;
}

// Montgomery form of v: v * R mod p. Split into 4 little-endian u64 limbs.
function montLimbs(v) {
  const mont = (v * R) % F;
  const limbs = [];
  let x = mont;
  for (let i = 0; i < 4; i++) { limbs.push(x & 0xffffffffffffffffn); x >>= 64n; }
  return limbs;
}

function limbsLiteral(v) {
  return '[' + montLimbs(v).map((l) => '0x' + l.toString(16).padStart(16, '0')).join(', ') + ']';
}

const C = RAW2.C.map(b64ToBig);       // 195 = 65 rounds * 3
const Mflat = RAW2.M.flat().map(b64ToBig); // 9 = 3x3

if (C.length !== 195) throw new Error('expected 195 C constants, got ' + C.length);
if (Mflat.length !== 9) throw new Error('expected 9 M constants, got ' + Mflat.length);

let out = '';
out += '// AUTO-GENERATED by scripts/gen_constants.js (run: node scripts/gen_constants.js) from\n';
out += '// ligeroclear/public/assets/poseidon1.js (poseidon-lite v0.3.0, t=3 / 2-to-1).\n';
out += '// Values are BN254-Fr round constants (C) and MDS matrix (M) in MONTGOMERY form\n';
out += '// (canonical * 2^256 mod p), stored as little-endian [u64; 4] limbs. DO NOT EDIT BY HAND.\n';
out += '#![cfg_attr(rustfmt, rustfmt_skip)]\n\n';
out += 'use crate::field::Fp;\n\n';
out += '/// Round constants, indexed C[round * 3 + lane], 65 rounds x 3 lanes.\n';
out += 'pub const C: [Fp; 195] = [\n';
for (let i = 0; i < C.length; i++) {
  out += '    Fp(' + limbsLiteral(C[i]) + '),\n';
}
out += '];\n\n';
out += '/// MDS matrix, row-major M[i*3 + j].\n';
out += 'pub const M: [Fp; 9] = [\n';
for (let i = 0; i < Mflat.length; i++) {
  out += '    Fp(' + limbsLiteral(Mflat[i]) + '),\n';
}
out += '];\n';

const dest = path.resolve(__dirname, '../src/constants.rs');
fs.writeFileSync(dest, out);
console.log('wrote', dest);

// --- Test vectors (computed by the reference itself) ---
require(REF);
const { poseidonV1Pair, poseidonV1HashElements } = globalThis.Poseidon1;
function hx(v) { return '0x' + v.toString(16).padStart(64, '0'); }

const x01 = (() => { let v = 0n; for (let i = 0; i < 32; i++) v = (v << 8n) | 0x01n; return v; })();
const x02 = (() => { let v = 0n; for (let i = 0; i < 32; i++) v = (v << 8n) | 0x02n; return v; })();
const fm1 = F - 1n;

console.log('\n// --- test vectors ---');
console.log('pair(0x01..01, 0x02..02) =', hx(poseidonV1Pair(x01, x02)));
console.log('pair(1,2)               =', hx(poseidonV1Pair(1n, 2n)));
console.log('pair(2,1)               =', hx(poseidonV1Pair(2n, 1n)));
console.log('single(42)  [=pair(42,0)]=', hx(poseidonV1HashElements([42n])));
console.log('pair(42,0)              =', hx(poseidonV1Pair(42n, 0n)));
console.log('single(0)               =', hx(poseidonV1HashElements([0n])));
console.log('single(F-1)             =', hx(poseidonV1HashElements([fm1])));
console.log('hash([10,20,30])        =', hx(poseidonV1HashElements([10n, 20n, 30n])));
const inner = poseidonV1HashElements([12345n]);
console.log('single(12345)           =', hx(inner));
console.log('single(single(12345))   =', hx(poseidonV1HashElements([inner])));
// A canonical reduction sanity vector and a couple of raw constants for the table self-check:
console.log('C[0] canonical          =', hx(b64ToBig(RAW2.C[0])));
console.log('C[3] canonical          =', hx(b64ToBig(RAW2.C[3])));
console.log('M[0] canonical          =', hx(b64ToBig(RAW2.M[0][0])));
